---
- name: Test vars
  assert:
    that:
      - foo | default(false)
      - foo is mapping
      - foo.a is defined
      - foo.a is number
      - foo.b | default(false)
      - foo.b is string
      - foo.c | default(false)
      - foo.c is sequence
    fail_msg: |
      foo: {{ foo }}

# vim:sw=2:ts=2:et:
